const ActionTypes = {
  GLOBAL_LOADING: 'GLOBAL_LOADING',
  GET_ARTICLES: 'GET_ARTICLES',
  GET_ARTICLES_SUCCESS: 'GET_ARTICLES_SUCCESS', 
  GET_ARTICLES_FAILED: 'GET_ARTICLES_FAILED',
  GET_TAGS: 'GET_TAGS',
  GET_ARTICLE_CONTENT: 'GET_ARTICLE_CONTENT',
  GET_ARTICLE_CONTENT_SUCCESS: 'GET_ARTICLE_CONTENT_SUCCESS',
  GET_COMMENTS: 'GET_COMMENTS',
  GET_ARTICLE_CONTENT_FAILD: 'SHOW_NOT_FOUNT_FAILD',
}

export default ActionTypes
