const ActionTypes = {
  GLOBAL_LOADING: 'GLOBAL_LOADING',
  GET_ARTICLES: 'GET_ARTICLES',
  GET_ARTICLES_SUCCESS: 'GET_ARTICLES_SUCCESS', 
  GET_ARTICLES_FAILED: 'GET_ARTICLES_FAILED',
  GET_TAGS: 'GET_TAGS'
}

export default ActionTypes
